use colored::Colorize;
use serde::{Deserialize, Serialize};
use std::path::Path;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum CodeOrigin {
    LikelyHuman,
    LikelyAiGenerated,
    LikelyGenerated,
    Unknown,
}

impl std::fmt::Display for CodeOrigin {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            CodeOrigin::LikelyHuman => write!(f, "human"),
            CodeOrigin::LikelyAiGenerated => write!(f, "AI-generated"),
            CodeOrigin::LikelyGenerated => write!(f, "code-gen"),
            CodeOrigin::Unknown => write!(f, "unknown"),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProvenanceResult {
    pub file: String,
    pub origin: CodeOrigin,
    pub confidence: f64,
    pub signals: Vec<String>,
}

/// Heuristic signals that suggest AI-generated code.
const AI_SIGNALS: &[(&str, f64)] = &[
    ("// Generated by", 0.9),
    ("// AUTO-GENERATED", 0.95),
    ("// This file was generated", 0.9),
    ("// ignore_for_file:", 0.1),
    ("TODO: implement", 0.3),
    ("TODO: add error handling", 0.4),
    ("// Placeholder", 0.3),
    ("throw UnimplementedError()", 0.35),
    ("print('TODO", 0.4),
];

/// Heuristic signals for build_runner / code generation.
const CODEGEN_SIGNALS: &[(&str, f64)] = &[
    (".g.dart", 0.95),
    (".freezed.dart", 0.95),
    (".gr.dart", 0.9),
    ("part of", 0.1),
    ("// GENERATED CODE - DO NOT MODIFY BY HAND", 0.99),
    ("// JsonSerializable", 0.5),
];

/// Analyze a single file for likely code origin.
pub fn analyze_provenance(file_path: &Path, source: &str) -> ProvenanceResult {
    let file_str = file_path.to_string_lossy().to_string();
    let mut ai_score: f64 = 0.0;
    let mut codegen_score: f64 = 0.0;
    let mut signals = Vec::new();

    for (pattern, weight) in CODEGEN_SIGNALS {
        if file_str.contains(pattern) || source.contains(pattern) {
            codegen_score += weight;
            signals.push(format!("code-gen: contains '{}'", pattern));
        }
    }

    if codegen_score > 0.8 {
        return ProvenanceResult {
            file: file_str,
            origin: CodeOrigin::LikelyGenerated,
            confidence: codegen_score.min(1.0),
            signals,
        };
    }

    for (pattern, weight) in AI_SIGNALS {
        if source.contains(pattern) {
            ai_score += weight;
            signals.push(format!("AI signal: contains '{}'", pattern));
        }
    }

    let lines: Vec<&str> = source.lines().collect();
    let total_lines = lines.len();

    if total_lines > 0 {
        let comment_lines = lines.iter().filter(|l| l.trim().starts_with("//")).count();
        let comment_ratio = comment_lines as f64 / total_lines as f64;
        if comment_ratio > 0.3 {
            ai_score += 0.15;
            signals.push(format!("High comment ratio: {:.0}%", comment_ratio * 100.0));
        }

        let empty_catch_blocks =
            source.matches("catch (e) {}").count() + source.matches("catch (e) {\n  }").count();
        if empty_catch_blocks > 0 {
            ai_score += 0.2 * empty_catch_blocks as f64;
            signals.push(format!(
                "{} empty catch blocks (common in AI code)",
                empty_catch_blocks
            ));
        }

        let unimplemented = source.matches("throw UnimplementedError()").count();
        if unimplemented > 1 {
            ai_score += 0.2;
            signals.push(format!("{} UnimplementedError throws", unimplemented));
        }

        let todo_count = source.matches("// TODO").count() + source.matches("// todo").count();
        if todo_count > 3 {
            ai_score += 0.15;
            signals.push(format!("{} TODO comments", todo_count));
        }
    }

    let (origin, confidence) = if ai_score > 0.6 {
        (CodeOrigin::LikelyAiGenerated, ai_score.min(1.0))
    } else if ai_score > 0.3 {
        (CodeOrigin::Unknown, ai_score)
    } else {
        (CodeOrigin::LikelyHuman, (1.0 - ai_score).min(1.0))
    };

    ProvenanceResult {
        file: file_str,
        origin,
        confidence,
        signals,
    }
}

/// Analyze all Dart files in a project for provenance using parallel processing.
pub fn analyze_project_provenance(root: &Path) -> anyhow::Result<Vec<ProvenanceResult>> {
    use rayon::prelude::*;

    let files: Vec<_> = walkdir::WalkDir::new(root)
        .into_iter()
        .filter_map(|e| match e {
            Ok(entry) => Some(entry),
            Err(err) => {
                log::warn!("Failed to read directory entry: {}", err);
                None
            }
        })
        .filter(|e| e.file_type().is_file())
        .filter(|e| e.path().extension().map_or(false, |ext| ext == "dart"))
        .map(|e| e.path().to_path_buf())
        .collect();

    let results: Vec<ProvenanceResult> = files
        .par_iter()
        .filter_map(|path| match std::fs::read_to_string(path) {
            Ok(source) => Some(analyze_provenance(path, &source)),
            Err(err) => {
                log::warn!("Failed to read {}: {}", path.display(), err);
                None
            }
        })
        .collect();

    Ok(results)
}

#[derive(Debug)]
pub struct ProvenanceSummary {
    pub total_files: usize,
    pub human_files: usize,
    pub ai_files: usize,
    pub codegen_files: usize,
    pub unknown_files: usize,
    pub ai_percentage: f64,
}

pub fn summarize_provenance(results: &[ProvenanceResult]) -> ProvenanceSummary {
    let total = results.len();
    let human = results
        .iter()
        .filter(|r| r.origin == CodeOrigin::LikelyHuman)
        .count();
    let ai = results
        .iter()
        .filter(|r| r.origin == CodeOrigin::LikelyAiGenerated)
        .count();
    let codegen = results
        .iter()
        .filter(|r| r.origin == CodeOrigin::LikelyGenerated)
        .count();
    let unknown = results
        .iter()
        .filter(|r| r.origin == CodeOrigin::Unknown)
        .count();

    let ai_pct = if total > 0 {
        ai as f64 / total as f64 * 100.0
    } else {
        0.0
    };

    ProvenanceSummary {
        total_files: total,
        human_files: human,
        ai_files: ai,
        codegen_files: codegen,
        unknown_files: unknown,
        ai_percentage: ai_pct,
    }
}

pub fn print_provenance_summary(summary: &ProvenanceSummary) {
    println!();
    println!(
        "  {} Code Provenance Analysis",
        "falcon".bright_cyan().bold()
    );
    println!();

    println!("  {} total files analyzed", summary.total_files);
    println!(
        "    {} Human-written    {}",
        "●".green(),
        summary.human_files.to_string().bright_white()
    );
    println!(
        "    {} AI-generated     {} ({:.1}%)",
        "●".bright_yellow(),
        summary.ai_files.to_string().bright_white(),
        summary.ai_percentage
    );
    println!(
        "    {} Code-generated   {}",
        "●".blue(),
        summary.codegen_files.to_string().bright_white()
    );
    println!(
        "    {} Unknown          {}",
        "●".dimmed(),
        summary.unknown_files.to_string().bright_white()
    );
    println!();
}
